/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa.e.report;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax. swing.table.DefaultTableModel;
/**
 *
 * @author Dooo
 */
public class Guru extends javax.swing.JFrame {

    private Statement st;
    private Connection con;
    private ResultSet rs; 
    DefaultTableModel model;
    DefaultTableModel model2;
    public Guru() {
        initComponents();
        koneksi_db data = new koneksi_db();
        data.koneksi();
        con = data.con;
        st = data.st;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
        String[] judul = {"NAMA","KELAS","MATEMATIKA","BAHASA INDONESIA","BAHASA INGGRIS","RATA-RATA"};
        model2 = new DefaultTableModel(judul,0);
        tabelNilai.setModel(model2);
        String[] nama = {"NAMA"};
        model = new DefaultTableModel(nama,0);
        tabelNama.setModel(model);
        
        tampilkan();
    }
    private void hapusData(){
            String[] options = {"Yes", "No"};
            JOptionPane.showOptionDialog(null, "Yakin Hapus Data Ini??", "Delete Confirm", 
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

            String nama = namaSiswa.getText();

            try {

            st = con.createStatement();
            String sqlUpdate = "DELETE FROM nilai WHERE nama='"+nama+"'";
            st.executeUpdate(sqlUpdate);
           
            clearField();
            

        JOptionPane.showMessageDialog(null, "Data Dihapus dari Database");
        tampilkan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus " + e.getMessage());
            }
        
        
        }
    private void ubahData(){
        String nama = namaSiswa.getText();
        String kelas = "";
        double mtk = Double.parseDouble(nilaiMtk.getText());
        double bindo = Double.parseDouble(nilaiBindo.getText());
        double bing = Double.parseDouble(nilaiBing.getText());
        double rerata = (mtk+bindo+bing)/3;
        
        if(kelasA.isSelected()){
                kelas = "9A";
            }else if(kelasB.isSelected()){
                kelas = "9B";
            }else if(kelasC.isSelected()){
                kelas = "9C";
            }else{
                kelas = "";
            }
        try {
            st = con.createStatement();
            
            
            String sql = "UPDATE `nilai` SET kelas='"+kelas+"',mtk='"+mtk+"',bindo='"+bindo+"',basing='"+bing+"',rerata='"+rerata+"' WHERE nama='"+nama+"' ";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Berhasil Diubah");
            tampilkan();
            
            clearField();
            } catch (SQLException e) {
                e.printStackTrace();
            } 
        
    }
    private void tambahData(){
        String nama = namaSiswa.getText();
        String kelas = "";
        double mtk = Double.parseDouble(nilaiMtk.getText());
        double bindo = Double.parseDouble(nilaiBindo.getText());
        double bing = Double.parseDouble(nilaiBing.getText());
        double rerata = (mtk+bindo+bing)/3;
        if(kelasA.isSelected()){
                kelas = "9A";
            }else if(kelasB.isSelected()){
                kelas = "9B";
            }else if(kelasC.isSelected()){
                kelas = "9C";
            }else{
                kelas = "";
            }
        try {
            st = con.createStatement();
            
            
            String sql = "INSERT INTO `nilai` (nama,kelas,mtk,bindo,basing,rerata) VALUES"+"('"+nama+"','"+kelas+"','"+mtk+"','"+bindo+"','"+bing+"','"+rerata+"')";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Berhasil Ditambahkan");
            tampilkan();
            
            clearField();
            } catch (SQLException e) {
                e.printStackTrace();
            } 
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        namaSiswa = new javax.swing.JTextField();
        nilaiMtk = new javax.swing.JTextField();
        nilaiBindo = new javax.swing.JTextField();
        nilaiBing = new javax.swing.JTextField();
        kelasA = new javax.swing.JRadioButton();
        kelasB = new javax.swing.JRadioButton();
        kelasC = new javax.swing.JRadioButton();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelNama = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelNilai = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        namaSiswa.setEditable(false);
        jPanel2.add(namaSiswa);
        namaSiswa.setBounds(470, 250, 340, 25);
        jPanel2.add(nilaiMtk);
        nilaiMtk.setBounds(520, 330, 290, 25);
        jPanel2.add(nilaiBindo);
        nilaiBindo.setBounds(520, 365, 290, 25);
        jPanel2.add(nilaiBing);
        nilaiBing.setBounds(520, 400, 290, 25);

        buttonGroup1.add(kelasA);
        kelasA.setText("9A");
        jPanel2.add(kelasA);
        kelasA.setBounds(460, 290, 60, 25);

        buttonGroup1.add(kelasB);
        kelasB.setText("9B");
        jPanel2.add(kelasB);
        kelasB.setBounds(550, 290, 43, 25);

        buttonGroup1.add(kelasC);
        kelasC.setText("9C");
        jPanel2.add(kelasC);
        kelasC.setBounds(630, 290, 43, 25);

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/tbhBtn.png"))); // NOI18N
        btnTambah.setText("jButton1");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel2.add(btnTambah);
        btnTambah.setBounds(393, 450, 130, 30);

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/ubahBtn.png"))); // NOI18N
        btnUbah.setText("jButton2");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel2.add(btnUbah);
        btnUbah.setBounds(629, 450, 138, 28);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/hapusBtn.png"))); // NOI18N
        btnHapus.setText("jButton3");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapus);
        btnHapus.setBounds(390, 510, 140, 30);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/logoutBtn.png"))); // NOI18N
        btnLogout.setText("jButton1");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout);
        btnLogout.setBounds(640, 510, 130, 30);

        tabelNama.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tabelNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelNamaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelNama);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(890, 380, 160, 130);

        tabelNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tabelNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelNilaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelNilai);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(0, 570, 1130, 180);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/pbo_003.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1130, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1131, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void tabelNamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelNamaMouseClicked
        DefaultTableModel model = (DefaultTableModel) tabelNama.getModel();
        int row = tabelNama.getSelectedRow();
        int col = tabelNama.getColumnCount();
        
        namaSiswa.setText(model.getValueAt(row,0).toString());
        tabelNama.setDefaultEditor(Object.class, null);
    }//GEN-LAST:event_tabelNamaMouseClicked

    private void tabelNilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelNilaiMouseClicked
        DefaultTableModel model = (DefaultTableModel) tabelNilai.getModel();
        int row = tabelNilai.getSelectedRow();
        int col = tabelNilai.getColumnCount();

        namaSiswa.setText(model.getValueAt(row,0).toString());
        String kelas = model.getValueAt(row, 1).toString();
        for (int i = 0;i<(buttonGroup1.getButtonCount());i++){
            if(kelas.equalsIgnoreCase(kelasA.getText())){
                kelasA.setSelected(rootPaneCheckingEnabled);
            }else if(kelas.equalsIgnoreCase(kelasB.getText())){
                kelasB.setSelected(rootPaneCheckingEnabled);
            }else if(kelas.equalsIgnoreCase(kelasC.getText())){
                kelasC.setSelected(rootPaneCheckingEnabled);
            }
            else{
                buttonGroup1.clearSelection();
            }
        }
        nilaiMtk.setText(model.getValueAt(row,2).toString());
        nilaiBindo.setText(model.getValueAt(row,3).toString());
        nilaiBing.setText(model.getValueAt(row,4).toString());
        
        tabelNilai.setDefaultEditor(Object.class, null);
    }//GEN-LAST:event_tabelNilaiMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        tambahData();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        ubahData();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton kelasA;
    private javax.swing.JRadioButton kelasB;
    private javax.swing.JRadioButton kelasC;
    private javax.swing.JTextField namaSiswa;
    private javax.swing.JTextField nilaiBindo;
    private javax.swing.JTextField nilaiBing;
    private javax.swing.JTextField nilaiMtk;
    private javax.swing.JTable tabelNama;
    private javax.swing.JTable tabelNilai;
    // End of variables declaration//GEN-END:variables
    private void tampilkan() {
        int row = tabelNilai.getRowCount();
        for (int i = 0;i<row;i++){
            model2.removeRow(0);
        }
        try {
        st = con.createStatement();
        rs = st.executeQuery("SELECT * FROM nilai");
        while(rs.next()){
            String[] data = {rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)};
            model2.addRow(data);
        }
        int row2 = tabelNama.getRowCount();
        for (int i = 0;i<row2;i++){
            model.removeRow(0);
        }
//        try {
        st = con.createStatement();
        rs = st.executeQuery("SELECT nama FROM `akun` WHERE role = 'Siswa'");
        while(rs.next()){
            String[] data = {rs.getString(1)};
            model.addRow(data);
        }
        if (con != null) {
            JOptionPane.showMessageDialog(null, "Wait Connecting Database");
        }
        
        }catch (Exception e) {
            e.printStackTrace();
        }
//        
    }
    private void clearField(){
        namaSiswa.requestFocus();
        nilaiMtk.setText("");
        nilaiBindo.setText("");
        nilaiBing.setText("");
        buttonGroup1.clearSelection();
    }
}
