/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa.e.report;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


public class Siswa extends javax.swing.JFrame {

    String keyword = Login.viewName;
    private Statement st;
    private Connection con;
    private ResultSet rs; 
    public Siswa() {
        initComponents();
        koneksi_db data = new koneksi_db();
        data.koneksi();
        con = data.con;
        st = data.st;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
            
        kelasSiswa.setText("9a");
        try {
        st = con.createStatement();
        rs = st.executeQuery("SELECT * FROM nilai WHERE nama IN (SELECT nama FROM `akun` WHERE username ='"+keyword+"')");
        while(rs.next()){
            String[] arr = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)};
            namaSiswa.setText(arr[1]);
            kelasSiswa.setText(arr[2]);
            nilaiMtk.setText(arr[3]);
            nilaiBindo.setText(arr[4]);
            nilaiBasing.setText(arr[5]);
            rerata.setText(arr[6]);
        }
        if (con != null) {
            JOptionPane.showMessageDialog(null, "Wait Connecting Database");
        }
        } catch (Exception e) {
            e.printStackTrace();
      }
    }
    public void viewData(){
        try {
        st = con.createStatement();
        rs = st.executeQuery("SELECT nama FROM `akun` WHERE username="+keyword);
        while(rs.next()){
            String[] data = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
            namaSiswa.setText(data[0]);
            kelasSiswa.setText("9b");
        }
        if (con != null) {
            JOptionPane.showMessageDialog(null, "Wait Connecting Database");
        }
        } catch (Exception e) {
            e.printStackTrace();
      }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        namaSiswa = new javax.swing.JTextField();
        kelasSiswa = new javax.swing.JTextField();
        nilaiMtk = new javax.swing.JTextField();
        nilaiBindo = new javax.swing.JTextField();
        nilaiBasing = new javax.swing.JTextField();
        rerata = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        namaSiswa.setEditable(false);
        jPanel2.add(namaSiswa);
        namaSiswa.setBounds(460, 254, 350, 25);

        kelasSiswa.setEditable(false);
        jPanel2.add(kelasSiswa);
        kelasSiswa.setBounds(460, 303, 350, 25);

        nilaiMtk.setEditable(false);
        nilaiMtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiMtkActionPerformed(evt);
            }
        });
        jPanel2.add(nilaiMtk);
        nilaiMtk.setBounds(520, 356, 290, 25);

        nilaiBindo.setEditable(false);
        nilaiBindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiBindoActionPerformed(evt);
            }
        });
        jPanel2.add(nilaiBindo);
        nilaiBindo.setBounds(520, 403, 290, 25);

        nilaiBasing.setEditable(false);
        nilaiBasing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiBasingActionPerformed(evt);
            }
        });
        jPanel2.add(nilaiBasing);
        nilaiBasing.setBounds(520, 450, 290, 25);

        rerata.setEditable(false);
        rerata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rerataActionPerformed(evt);
            }
        });
        jPanel2.add(rerata);
        rerata.setBounds(520, 497, 290, 25);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/logoutBtn.png"))); // NOI18N
        btnLogout.setText("jButton1");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout);
        btnLogout.setBounds(510, 548, 130, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/pbo_004.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(1, -4, 1130, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void rerataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rerataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rerataActionPerformed

    private void nilaiBindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiBindoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiBindoActionPerformed

    private void nilaiMtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiMtkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiMtkActionPerformed

    private void nilaiBasingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiBasingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiBasingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kelasSiswa;
    private javax.swing.JTextField namaSiswa;
    private javax.swing.JTextField nilaiBasing;
    private javax.swing.JTextField nilaiBindo;
    private javax.swing.JTextField nilaiMtk;
    private javax.swing.JTextField rerata;
    // End of variables declaration//GEN-END:variables
    
}
